### ISSUE TITLE
Icons for localization.

### ISSUE THREAD

**Issue by bosd** [spilymp/ibo#9]
Is it possible to include: https://github.com/boydjd/FontCountry
for localizations?
example:
￼

**Comment by spilymp** [comment]
Hello,

thank you very much for your patience and interest in the project. You can add any additional icon sets or your own icons locally or in a fork. Within the project currently only icon sets are included that can be hosted externally/included via a single link. The set you suggested does not offer that from my point of view. 

But I am happy to be taught better or to be shown a simple way of integration (without having to include the files into the project). Otherwise the mentioned icon set will not be included in the project by default, thank you for understanding.
